/*
      <div class="col-sm-4">
        <div class="panel panel-warning">
          <div class="panel-heading">BLACK FRIDAY DEAL</div>
          <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" 
               class="img-responsive"
              style="width:100%" alt="Image"></div>
          <div class="panel-footer">Buy 50 mobiles and get a gift card</div>
        </div>
      </div>
*/

const products = [
   {
      code: 1,
      name: "Super control Collar",
      brand: "Dupper",
      description: "leather collar with leash",
      animal: "dog",
      category: "wear",
      subcategory: "collars & leashes",
      size: "S",
      price: 8.0,
      quantity: 10,
   },
   {
      code: 2,
      name: "Super Control CAT Collar",
      brand: "Dupper",
      description: "leather collar with leash",
      animal: "cat",
      category: "wear",
      subcategory: "collars & leashes",
      size: "M",
      price: 10,
      quantity: 10,
   },
   {
      code: 3,
      name: "Super License Collar",
      brand: "Dupper",
      description: "leather collar for licence",
      animal: "dog",
      category: "wear",
      subcategory: "collars & leashes",
      size: "All",
      price: 10,
      quantity: 20,
   },
   {
      code: 4,
      name: "Extra Strong Chain",
      brand: "Channat",
      description: "reforced chain leash",
      animal: "dog",
      category: "wear",
      subcategory: "collars & leashes",
      size: "1.5m",
      price: 25,
      quantity: 20,
   },
   {
      code: 5,
      name: "Extra Confy Kitty Jacket",
      brand: "Cute Warm",
      description: "Wool Hooded Jacket",
      animal: "cat",
      category: "wear",
      subcategory: "Vests & Jackets",
      size: "S",
      price: 25,
      quantity: 10,
   },
   {
      code: 6,
      name: "Extra Confy Jacket",
      brand: "Cute Warm",
      description: "Wool Hooded Jacket",
      animal: "dog",
      category: "wear",
      subcategory: "Vests & Jackets",
      size: "M",
      price: 30,
      quantity: 10,
   },
   {
      code: 7,
      name: "Extra Confy Jacket",
      brand: "Cute Warm",
      description: "Wool Hooded Jacket",
      animal: "dog",
      category: "wear",
      subcategory: "Vests & Jackets",
      size: "L",
      price: 33,
      quantity: 10,
   },
   {
      code: 8,
      name: "Extra Confy Jacket",
      brand: "Cute Warm",
      description: "Wool Hooded Jacket",
      animal: "dog",
      category: "wear",
      subcategory: "Vests & Jackets",
      size: "XL",
      price: 40,
      quantity: 5,
   },
   {
      code: 9,
      name: "Extra Confy Kitty Jacket",
      brand: "Cute Warm",
      description: "Wool Hooded Jacket",
      animal: "cat",
      category: "wear",
      subcategory: "Vests & Jackets",
      size: "XS",
      price: 35,
      quantity: 15,
   },
   {
      code: 10,
      name: "The fishy",
      brand: "Cute Warm",
      description: "Fish style dog swim suit",
      animal: "dog",
      category: "wear",
      subcategory: "Vests & Jackets",
      size: "S",
      price: 40,
      quantity: 0,
   },
   {
      code: 11,
      name: "Crunchy",
      brand: "Heathy Farm",
      description: "Complete beef dry dog food",
      animal: "dog",
      category: "food",
      subcategory: "dry food",
      size: "X",
      price: 40,
      quantity: 10,
   },
   {
      code: 12,
      name: "Yummy",
      brand: "Heathy Farm",
      description: "Complete beef wet cat food",
      animal: "cat",
      category: "food",
      subcategory: "dry food",
      size: "S",
      price: 10,
      quantity: 10,
   },
];
